[package]
name = "writingbuddy"
version = "0.5.0"
authors = ["Thomas Niederberger <thomas@niederb.ch>"]
edition = "2021"

license = "MIT OR Apache-2.0"

description = "A tool to help you create a writing habit"
readme = "README.md"
homepage = "https://github.com/niederb/writingbuddy"
repository = "https://github.com/niederb/writingbuddy"
keywords = ["cli", "tool", "writing", "text"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
config = "0.11"
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
crossterm = "0.22"
textwrap = "0.14"
structopt = "0.3"
stopwatch = "0.0"