# Filename and path to which to append the written text
# See this link for a list of specifiers you can use in the string:
# https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# Default: "%Y-%m.md"
file_string = "%Y-%m.md"

# Default title to propose for a new text
# See this link for a list of specifiers you can use in the string:
# https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# Default: "## %Y-%m-%d"
title_string = "## %Y-%m-%d"

# Whether or not the backspace key is enabled while writing.
# This is meant to help you continue writing without losing focus because you start correcting your text.
# Default: true
backspace_active = true

# How many words you want to write. 0 means no word count goal.
# Default: 0
goal_words = 75

# Amount of time in seconds you want to spend writing. 0 means no time goal.
# Default: 0
goal_time = 60

# In strict mode you cannot stop writing until you reach your defined goals.
# Default: true
strict_mode = true

# If you don't type for `keystroke_timeout` seconds your text will be cleared.
# Forces you to keep on typing. Set to 0 to disable.
# Default: 0
keystroke_timeout = 5